In [2]:
# 打開瀏覽器

from selenium import webdriver
from selenium.webdriver.support.ui import Select
from bs4 import BeautifulSoup
executable_path="D:\Anaconda3\Lib\site-packages\chromedriver.exe" 
browser = webdriver.Chrome(executable_path)

browser.get("http://taqm.epa.gov.tw/taqm/tw/MonthlyAverage.aspx")

In [3]:
# 模擬使用者操作行為，選擇/點擊

selectSite = Select(browser.find_element_by_id("ctl05_ddlSite"))
selectSite.select_by_value('29')
selectYear = Select(browser.find_element_by_id("ctl05_ddlYear"))
selectYear.select_by_value('2014')

browser.find_element_by_id('ctl05_btnQuery').click()

In [4]:
# 取得資料，丟到 BeautifulSoup 解析

html_source = browser.page_source

soup = BeautifulSoup(html_source, 'html.parser')
table = soup.find('table', class_='TABLE_G')
print(table)

<table align="Center" border="1" cellpadding="3" cellspacing="0" class="TABLE_G" id="ctl05_gv" rules="all" style="border-color:Black;border-width:1px;border-style:None;border-collapse:collapse;">
<tbody><tr style="color:Black;font-weight:normal;">
<th scope="col">監測項目</th><th scope="col">單位</th><th scope="col">監測日期</th><th scope="col">監測值</th><th scope="col">標註</th>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">SO2</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2014/01</td><td>4.20</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/02</td><td>2.50</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/03</td><td>3.80</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/04</td><td>3.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/05</td><td>3.10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/06</td><td>3</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/07</td><td>3.70</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/08</td><td>3.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/09</td><td>3.70</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/10</td><td>2.80</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/11</td><td>2.70</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/12</td><td>3.10</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">CO</td><td class="no-alt" rowspan="12" valign="top">ppm</td><td>2014/01</td><td>0.48</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/02</td><td>0.38</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/03</td><td>0.47</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/04</td><td>0.39</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/05</td><td>0.35</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/06</td><td>0.27</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/07</td><td>0.22</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/08</td><td>0.23</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/09</td><td>0.31</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/10</td><td>0.35</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/11</td><td>0.41</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/12</td><td>0.42</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">O3</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2014/01</td><td>30.70</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/02</td><td>31.90</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/03</td><td>35.10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/04</td><td>41.50</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/05</td><td>26.80</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/06</td><td>23.50</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/07</td><td>24.30</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/08</td><td>24.70</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/09</td><td>27.60</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/10</td><td>43.20</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/11</td><td>32.80</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/12</td><td>28.80</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">PM10</td><td class="no-alt" rowspan="12" valign="top">μg/m3</td><td>2014/01</td><td>72</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/02</td><td>50</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/03</td><td>74</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/04</td><td>64</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/05</td><td>39</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/06</td><td>34</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/07</td><td>35</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/08</td><td>32</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/09</td><td>47</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/10</td><td>69</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/11</td><td>67</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/12</td><td>60</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NOx</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2014/01</td><td>23.63</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/02</td><td>16.89</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/03</td><td>21.78</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/04</td><td>17.06</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/05</td><td>16.66</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/06</td><td>13.82</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/07</td><td>12.16</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/08</td><td>12.46</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/09</td><td>15.15</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/10</td><td>16.72</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/11</td><td>18.61</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/12</td><td>19.20</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NO</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2014/01</td><td>4.75</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/02</td><td>2.53</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/03</td><td>3.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/04</td><td>1.56</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/05</td><td>2.37</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/06</td><td>2.17</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/07</td><td>2.04</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/08</td><td>2.09</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/09</td><td>2</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/10</td><td>1.88</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/11</td><td>2.63</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/12</td><td>3.17</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NO2</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2014/01</td><td>18.88</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/02</td><td>14.36</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/03</td><td>18.38</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/04</td><td>15.49</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/05</td><td>14.28</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/06</td><td>11.65</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/07</td><td>10.11</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/08</td><td>10.36</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/09</td><td>13.14</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/10</td><td>14.82</td><td> </td>
</tr><tr style="color:Black;">
<td>2014/11</td><td>15.98</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2014/12</td><td>16.02</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="1" style="white-space:nowrap;" valign="top">THC</td><td class="no-alt" rowspan="1" valign="top">ppm</td><td> </td><td> </td><td>無此測項</td>
</tr><tr class="ALT" style="color:Black;">
<td class="no-alt" rowspan="1" style="white-space:nowrap;" valign="top">NMHC</td><td class="no-alt" rowspan="1" valign="top">ppm</td><td> </td><td> </td><td>無此測項</td>
</tr><tr style="color:Black;">
<td style="white-space:nowrap;">CH4</td><td>ppm</td><td> </td><td> </td><td>無此測項</td>
</tr>
</tbody></table>

In [5]:
# 關閉瀏覽器
browser.quit();

In [7]:
#查詢台北市士林區 2018/01 – 2018/08 的 SO2 資料
browser = webdriver.Chrome(executable_path)
browser.get("http://taqm.epa.gov.tw/taqm/tw/MonthlyAverage.aspx")
selectYear = Select(browser.find_element_by_id("ctl05_ddlYear"))
selectYear.select_by_value('2018')
browser.find_element_by_id('ctl05_btnQuery').click()

In [10]:
html_source = browser.page_source
soup = BeautifulSoup(html_source, 'html.parser')
table = soup.find('table', class_='TABLE_G')
print(table)

<table align="Center" border="1" cellpadding="3" cellspacing="0" class="TABLE_G" id="ctl05_gv" rules="all" style="border-color:Black;border-width:1px;border-style:None;border-collapse:collapse;">
<tbody><tr style="color:Black;font-weight:normal;">
<th scope="col">監測項目</th><th scope="col">單位</th><th scope="col">監測日期</th><th scope="col">監測值</th><th scope="col">標註</th>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">SO2</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2018/01</td><td>1.80</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>1.90</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>2.20</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>2.30</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>3.10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>2.70</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>2.20</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>2.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>2.10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>1.70</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>1.90</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>1.80</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">CO</td><td class="no-alt" rowspan="12" valign="top">ppm</td><td>2018/01</td><td>0.34</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>0.44</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>0.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>0.38</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>0.34</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>0.29</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>0.21</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>0.30</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>0.26</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>0.29</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>0.30</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>0.35</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">O3</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2018/01</td><td>33.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>32.50</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>35</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>38.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>31.60</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>29.50</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>18.70</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>26.40</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>29.10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>45.90</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>32.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>30.70</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">PM10</td><td class="no-alt" rowspan="12" valign="top">μg/m3</td><td>2018/01</td><td>23</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>41</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>39</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>48</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>37</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>26</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>24</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>26</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>28</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>33</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>25</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>21</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NOx</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2018/01</td><td>14.17</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>19.43</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>18.50</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>15.24</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>15.20</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>13.79</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>11.60</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>14.75</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>12.40</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>12.45</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>13.41</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>14.56</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NO</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2018/01</td><td>3.41</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>4.48</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>4.93</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>2.60</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>2.26</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>2.41</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>2.68</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>2.68</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>2.41</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>2.13</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>2.71</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>3.42</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="12" style="white-space:nowrap;" valign="top">NO2</td><td class="no-alt" rowspan="12" valign="top">ppb</td><td>2018/01</td><td>10.77</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/02</td><td>14.95</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/03</td><td>13.56</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/04</td><td>12.64</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/05</td><td>12.94</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/06</td><td>11.38</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/07</td><td>8.92</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/08</td><td>12.08</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/09</td><td>10</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/10</td><td>10.33</td><td> </td>
</tr><tr style="color:Black;">
<td>2018/11</td><td>10.71</td><td> </td>
</tr><tr class="ALT" style="color:Black;">
<td>2018/12</td><td>11.15</td><td> </td>
</tr><tr style="color:Black;">
<td class="no-alt" rowspan="1" style="white-space:nowrap;" valign="top">THC</td><td class="no-alt" rowspan="1" valign="top">ppm</td><td> </td><td> </td><td>無此測項</td>
</tr><tr class="ALT" style="color:Black;">
<td class="no-alt" rowspan="1" style="white-space:nowrap;" valign="top">NMHC</td><td class="no-alt" rowspan="1" valign="top">ppm</td><td> </td><td> </td><td>無此測項</td>
</tr><tr style="color:Black;">
<td style="white-space:nowrap;">CH4</td><td>ppm</td><td> </td><td> </td><td>無此測項</td>
</tr>
</tbody></table>

In [11]:
t = {}
for tr in table.find_all('tr')[1:]:

    for i, td in enumerate(tr.find_all('td')):
        
        if len(tr.find_all('td')) == 5:
            if i == 0:
                obs = td.text
                t.setdefault(obs, {})
            if i == 2:
                date = td.text
            if i == 3:
                value = td.text
                t[obs][date] = value
        
        if len(tr.find_all('td')) == 3:
            if i == 0:
                date = td.text
            if i == 1:
                value = td.text
                t[obs][date] = value
print(t)

{'SO2': {'2018/01': '1.80', '2018/02': '1.90', '2018/03': '2.20', '2018/04': '2.30', '2018/05': '3.10', '2018/06': '2.70', '2018/07': '2.20', '2018/08': '2.40', '2018/09': '2.10', '2018/10': '1.70', '2018/11': '1.90', '2018/12': '1.80'}, 'CO': {'2018/01': '0.34', '2018/02': '0.44', '2018/03': '0.40', '2018/04': '0.38', '2018/05': '0.34', '2018/06': '0.29', '2018/07': '0.21', '2018/08': '0.30', '2018/09': '0.26', '2018/10': '0.29', '2018/11': '0.30', '2018/12': '0.35'}, 'O3': {'2018/01': '33.40', '2018/02': '32.50', '2018/03': '35', '2018/04': '38.40', '2018/05': '31.60', '2018/06': '29.50', '2018/07': '18.70', '2018/08': '26.40', '2018/09': '29.10', '2018/10': '45.90', '2018/11': '32.40', '2018/12': '30.70'}, 'PM10': {'2018/01': '23', '2018/02': '41', '2018/03': '39', '2018/04': '48', '2018/05': '37', '2018/06': '26', '2018/07': '24', '2018/08': '26', '2018/09': '28', '2018/10': '33', '2018/11': '25', '2018/12': '21'}, 'NOx': {'2018/01': '14.17', '2018/02': '19.43', '2018/03': '18.50', '2018/04': '15.24', '2018/05': '15.20', '2018/06': '13.79', '2018/07': '11.60', '2018/08': '14.75', '2018/09': '12.40', '2018/10': '12.45', '2018/11': '13.41', '2018/12': '14.56'}, 'NO': {'2018/01': '3.41', '2018/02': '4.48', '2018/03': '4.93', '2018/04': '2.60', '2018/05': '2.26', '2018/06': '2.41', '2018/07': '2.68', '2018/08': '2.68', '2018/09': '2.41', '2018/10': '2.13', '2018/11': '2.71', '2018/12': '3.42'}, 'NO2': {'2018/01': '10.77', '2018/02': '14.95', '2018/03': '13.56', '2018/04': '12.64', '2018/05': '12.94', '2018/06': '11.38', '2018/07': '8.92', '2018/08': '12.08', '2018/09': '10', '2018/10': '10.33', '2018/11': '10.71', '2018/12': '11.15'}, 'THC': {'\xa0': '\xa0'}, 'NMHC': {'\xa0': '\xa0'}, 'CH4': {'\xa0': '\xa0'}}

In [16]:
print("台北市士林區 2018 的 SO2 資料")
print(t['SO2'])
print("台北市士林區 2018/01 – 2018/08 的 SO2 資料")
#參考查詢方式
print(dict([(key, value) for key, value in t['SO2'].items() if key < '2018/09' ]))

台北市士林區 2018 的 SO2 資料
{'2018/01': '1.80', '2018/02': '1.90', '2018/03': '2.20', '2018/04': '2.30', '2018/05': '3.10', '2018/06': '2.70', '2018/07': '2.20', '2018/08': '2.40', '2018/09': '2.10', '2018/10': '1.70', '2018/11': '1.90', '2018/12': '1.80'}
台北市士林區 2018/01 – 2018/08 的 SO2 資料
{'2018/01': '1.80', '2018/02': '1.90', '2018/03': '2.20', '2018/04': '2.30', '2018/05': '3.10', '2018/06': '2.70', '2018/07': '2.20', '2018/08': '2.40'}

In [14]:
#參考寫法
import pandas as pd
F=[{'時間': key, '數值': value} for key, value in t['SO2'].items() if key < '2018/09' ]
pd.DataFrame(F)

        時間    數值
0  2018/01  1.80
1  2018/02  1.90
2  2018/03  2.20
3  2018/04  2.30
4  2018/05  3.10
5  2018/06  2.70
6  2018/07  2.20
7  2018/08  2.40

In [18]:
#台北市士林區 2018/01 – 2018/08 的 SO2、CO 資料
d_SO2 = [{'時間': key, 'SO2': value} for key, value in t['SO2'].items() if key < '2018/09' ]
d_CO = [{'時間': key, 'CO': value} for key, value in t['CO'].items() if key < '2018/09' ]
pd.merge(pd.DataFrame(d_SO2), pd.DataFrame(d_CO))

        時間   SO2    CO
0  2018/01  1.80  0.34
1  2018/02  1.90  0.44
2  2018/03  2.20  0.40
3  2018/04  2.30  0.38
4  2018/05  3.10  0.34
5  2018/06  2.70  0.29
6  2018/07  2.20  0.21
7  2018/08  2.40  0.30